# Generated by Django 4.0 on 2022-04-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='bg_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='main_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='position',
            field=models.CharField(blank=True, default='center', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='size',
            field=models.CharField(blank=True, default='desktop', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='thanks_bg_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='thanks_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='thanks_text',
            field=models.CharField(blank=True, default='Благодарим Вас за предоставленную информацию', max_length=255, null=True),
        ),
    ]
